travis:
  secure:
    BINSTAR_TOKEN: SW8grNPkV/EH7Z/tVEtJQ9qGPEDKLfHmPSvo2FaUiQTGhSHvBxTzSZjZxXIE4lk5XJ4HPrhKfZ0ZTofVRC1+NB2tAgq/WzuIZN2TknF3MmvJV+X45VuNHfLlXX3e7aQFDpcFUPNufXhGhBWr3fwp62ExBf+3ETAhdQNzPGJoN0pS6RssGgN+bUJxtWdNC8mXrKQxnpamiYNk32lYk7woZ9eDyYcfAEGHzlqyK1aImlRGV9JtHt0ANGEYYbdOzCjoz2CCOoHwVQ7deymFkjYtevVTLgdR7TB0vtoZ3ESeozfkWUnCs3ObBJEjuLoFh5Udmhx+4Dj4HyAvKX61NVnoyrFzbK/RUy4YWj2qGZLhXkdNYTcctR6pYzaW83SEXo5vNU+nIBBmNyguCHsB1ylCIuCVR/tjYDNZYsLQgDItKwu97FdIbXcmpOUZeOtv0P/LUid9HdJqYzi3/adESk5wfc2SANW9mbn8qrAMdek9wxWenPSgbMmXfhXVBP/GINcW9i0r8L95HV0N6wUQ6E8KVTHUqVfISHVfFKYVpeRDkHsC3cOETeihf1xDLkN4kbyhwuiapdwADjL/i0C7tQO8WjuKpfo6J0hnLcvcyBZOSHBoL/L6aoeWyRbknSbnba5sOQB1vnNY54NHZkwLIvY860s0weOeqROqeb4EYBdL6Iw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
