travis:
  secure:
    BINSTAR_TOKEN: uz1X7oBGzZ97DOJ+tnFHky2QY71IwUiktsWizQDUjTBKXaYg5T9gNLGoUsOcxGZhP5CdHAiowMUs1z+CXX+QxyRy3GgihAb5xjo8ntDbquGwqJSSclC1vY5Sv/FoOz2c93hzYTyZTjxpOV40vD1IaDvAICLuf80uZVYZNlK0l2ybMnopAnHZrFztrip9vBL+PthizUfRBYBMP8nRpLnI/P7L0gqHxY0EL5pyJjUWAD4bS6tB1dB43hJ31eo1VKAV/ncp+Gb4uf+E7AWRlG4ouabvldh9MAqW45HYbuqZsvcHCJJslKYiTW5AkNCsM+VS0r0C7TQ5Gjj6yf8ziWlNZoAnFmE+Bi2EfToWXtV74R1gyULro3PtUB2nWlvR+S1O6YOktSvMvx4yX90udho4czWV/vWg+TpVix8wn5ufXptMnfxP3y1U6mjtvbGzR86lPAJqQbfvQ6zHRzssogBBrhYbkC5W+6nEWl4sUhwJmZCyui30fg4fBRM9C3sT87YctoRcbU4U1LbYlUAYW+rNKfvpI2kvoYIHufIL9G1yelmpKuY5PEyEHIZvquEEJzE8MUxaazg/TV+7a/0sDTplqcG6fRJ1sLx+IR/cm+YRL1UgeGJdx3OiYdfFjYCK669CcGbBe7fzFfFNJghPyQhbQ5Wtxrzpb8/J/NtWA4LixuM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
